services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - OPENAI_API_KEY=sk-Zx-ulKR2hOEMKJRzJjBCUD7Ur_CJL692TZGgyxIwbST3BlbkFJFPe6_IocSBIU4PNfpmGr1iWZRAKsXKfOZ8795PzDwA
    volumes:
      - ./backend:/app
      - /app/node_modules

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - VITE_API_URL=http://localhost:9000  # Use service name
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge