services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env   # This loads environment variables from the .env file
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - ./frontend/.env   # This loads environment variables from the .env file

networks:
  app-network:
    driver: bridge
